<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24240" started-at="2019-04-03T07:44:48Z" finished-at="2019-04-03T07:45:12Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24240" started-at="2019-04-03T07:44:48Z" finished-at="2019-04-03T07:45:12Z">
      <class name="SampleMavenProject.SampleMavenProject.TestCases">
        <test-method status="PASS" signature="alaunch()[pri:0, instance:SampleMavenProject.SampleMavenProject.TestCases@783e6358]" name="alaunch" duration-ms="24169" started-at="2019-04-03T07:44:48Z" finished-at="2019-04-03T07:45:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alaunch -->
        <test-method status="FAIL" signature="launch()[pri:0, instance:SampleMavenProject.SampleMavenProject.TestCases@783e6358]" name="launch" duration-ms="0" started-at="2019-04-03T07:45:12Z" finished-at="2019-04-03T07:45:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at SampleMavenProject.SampleMavenProject.Utility_Maven.launchApp(Utility_Maven.java:17)
at SampleMavenProject.SampleMavenProject.TestCases.launch(TestCases.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
      </class> <!-- SampleMavenProject.SampleMavenProject.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
